server:
  port: 8002

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username:  root
    url: jdbc:mysql://192.168.118.131:3306/youshe?serverTimezone=GMT%2B8
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: YouSheHikariPool
  #  设置返回json的统一时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    database: 1
    host: 120.55.51.37
    port: 6379
    password: feng10.10
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      # 逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
    type-aliases-package: com.youshe.mcp.entity


# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration:  604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

## 阿里云 OSS
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com # 地域节点
      keyid: LTAI5tFNjjg1s5mtpDC6Rxc4 # AccessKeyId
      keysecret: fZvVNtbU8pNfmAPas53jYXhMUVHOo8 # 密钥
      bucketname: youshe-xiuyuan # bucket名字




